version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      KAFKA_HOST: kafka:9092
      POSTGRES_HOST: postgis
      POSTGRES_DB: geodb
      POSTGRES_USER: geo
      POSTGRES_PASSWORD: secret
    depends_on:
      - kafka
      - postgis

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  postgis:
    image: postgis/postgis:14-3.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: geodb
      POSTGRES_USER: geo
      POSTGRES_PASSWORD: secret