version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: postgis
      POSTGRES_DB: geodb
      POSTGRES_USER: geo
      POSTGRES_PASSWORD: secret
    depends_on:
      - postgis
    restart: unless-stopped

  postgis:
    image: postgis/postgis:14-3.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: geodb
      POSTGRES_USER: geo
      POSTGRES_PASSWORD: secret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U geo"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data