apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: lucaspark7/backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_HOST
              value: postgis
            - name: POSTGRES_DB
              value: geodb
            - name: POSTGRES_USER
              value: geo
            - name: POSTGRES_PASSWORD
              value: secret
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
      restartPolicy: Always